// examples/vite-project-solid/src/main.tsx
import { render } from "solid-js/web"
import { I18nProvider } from "@lingui/solid"
import { setupI18n } from "@lingui/core"
import { App } from "./App"
import "./index.css"
import { loadCatalog } from "./i18n"

const i18n = setupI18n()
await loadCatalog("en", i18n)

render(
  () => (
    <I18nProvider i18n={i18n}>
      <App />
    </I18nProvider>
  ),
  document.getElementById("root") as HTMLElement,
)

// examples/vite-project-react-babel/src/main.tsx
import React from "react"
import ReactDOM from "react-dom/client"
import { App } from "./App"
import "./index.css"
import { setupI18n } from "@lingui/core"
import { I18nProvider } from "@lingui/react"
import { loadCatalog } from "./i18n"

const i18n = setupI18n()
await loadCatalog("en", i18n)

ReactDOM.createRoot(document.getElementById("root") as HTMLElement).render(
  <React.StrictMode>
    <I18nProvider i18n={i18n}>
      <App />
    </I18nProvider>
  </React.StrictMode>,
)
