// examples/rspack/src/main.tsx
import React from "react";
import { createRoot } from "react-dom/client";

import { i18n } from "@lingui/core";
import { I18nProvider } from "@lingui/react";
import { messages as enMessages } from "./locales/en/messages";
import { messages as frMessages } from "./locales/fr/messages";

import Inbox from "./Inbox";

i18n.load({
  "en": enMessages,
  "fr": frMessages,
});

i18n.activate("en");

const App = () => (
  <I18nProvider i18n={i18n}>
    <Inbox />
  </I18nProvider>
);

const container = document.getElementById('root');
const root = createRoot(container!);
root.render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
)

// examples/vite-project-solid/src/main.tsx
import { render } from "solid-js/web"
import { I18nProvider } from "@lingui/solid"
import { setupI18n } from "@lingui/core"
import { App } from "./App"
import "./index.css"
import { loadCatalog } from "./i18n"

const i18n = setupI18n()
await loadCatalog("en", i18n)

render(
  () => (
    <I18nProvider i18n={i18n}>
      <App />
    </I18nProvider>
  ),
  document.getElementById("root") as HTMLElement,
)
