// packages/solid/src/TransNoContext.tsx
import { createMemo, JSX, ParentComponent } from "solid-js"
import { formatElements } from "./format"
import type { MessageOptions } from "@lingui/core"
import { Dynamic } from "solid-js/web"
import { I18nContext } from "./I18nProvider"

export type TransRenderProps = {
  id: string
  translation: JSX.Element
  children: JSX.Element
  message?: string | null
}

export type TransRenderCallbackOrComponent =
  | {
      component?: undefined
      render?:
        | ((props: TransRenderProps) => JSX.Element)
        | null
    }
  | {
      component?: ParentComponent<TransRenderProps> | null
      render?: undefined
    }

export type TransProps = {
  id: string
  message?: string
  values?: Record<string, unknown>
  components?: { [key: string]: JSX.Element | any }
  formats?: MessageOptions["formats"]
  comment?: string
  children?: JSX.Element
} & TransRenderCallbackOrComponent

/**
 * Version of `<Trans>` component without using a Provider/Context SolidJS feature.
 *
 * @experimental the api of this component is not stabilized yet.
 */
export const TransNoContext: ParentComponent<TransProps & {
  lingui: I18nContext
}> = (props) => {
  const translatedContent = createMemo(() => {
    const values = { ...props.values ?? {} }
    const components = { ...props.components ?? {} }

    if (props.values) {
      /*
        Related discussion: https://github.com/lingui/js-lingui/issues/183

        Values *might* contain html elements with static content.
        They're replaced with <INDEX /> placeholders and added to `components`.

        Example:
        Translation: 'Hello {name}'
        Values: { name: <strong>Jane</strong> }

        It'll become "Hello <0 />" with components=[<strong>Jane</strong>]
      */
      Object.keys(props.values).forEach((key) => {
        const index = Object.keys(components).length

        // simple scalars should be processed as values to be able to apply formatting
        if (typeof values[key] === "string" || typeof values[key] === "number") {
          return
        }

        // falsy values should be empty string
        if (!values[key]) {
          values[key] = ""
          return
        }

        // html nodes, arrays
        components[index] = values[key]
        values[key] = `<${index}/>`
      })
    }

    const _translation: string =
      props.lingui.i18n != null && typeof props.lingui.i18n()._ === "function"
        ? props.lingui.i18n()._(props.id, values, { message: props.message, formats: props.formats })
        : props.id // i18n provider isn't loaded at all

    const translation = _translation ? formatElements(_translation, components) : null

    if (props.render === null || props.component === null) {
      // Although `string` is a valid SolidJS element, types only allow `Element`
      // Upstream issue: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/20544
      return translation as unknown as JSX.Element
    }

    const FallbackComponent: ParentComponent<TransRenderProps> =
      props.lingui.defaultComponent() || RenderFragment

    const i18nProps: TransRenderProps = {
      id: props.id,
      message: props.message,
      translation,
      children: translation, // for type-compatibility with `component` prop
    }

    // Validation of `render` and `component` props
    if (props.render && props.component) {
      console.error(
        "You can't use both `component` and `render` prop at the same time. `component` is ignored."
      )
    } else if (props.render && typeof props.render !== "function") {
      console.error(
        `Invalid value supplied to prop \`render\`. It must be a function, provided ${props.render}`
      )
    } else if (props.component && typeof props.component !== "function") {
      console.error(
        `Invalid value supplied to prop \`component\`. It must be a SolidJS component, provided ${props.component}`
      )
      return <Dynamic component={FallbackComponent} {...i18nProps}>{translation}</Dynamic>
    }

    // Rendering using a render prop
    if (typeof props.render === "function") {
      // Component: render={(props) => <a title={props.translation}>x</a>}
      return props.render(i18nProps)
    }

    // `component` prop has a higher precedence over `defaultComponent`
    const Component: ParentComponent<TransRenderProps> =
      props.component || FallbackComponent

    return <Dynamic component={Component} {...i18nProps}>{translation}</Dynamic>
  })
  return <>{translatedContent()}</>

}

const RenderFragment: ParentComponent<TransRenderProps> = (props) => {
  // cannot use <></> directly because we're passing in props that it doesn't support
  return <>{props.children}</>
}

// packages/react/src/TransNoContext.tsx
import { formatElements } from "./format"
import type { I18n, MessageOptions } from "@lingui/core"

export type TransRenderProps = {
  id: string
  translation: React.ReactNode
  children: React.ReactNode
  message?: string | null
}

export type TransRenderCallbackOrComponent =
  | {
      component?: never
      render?:
        | ((props: TransRenderProps) => React.ReactElement<any, any>)
        | null
    }
  | {
      component?: React.ComponentType<TransRenderProps> | null
      render?: never
    }

export type TransProps = {
  id: string
  message?: string
  values?: Record<string, unknown>
  components?: { [key: string]: React.ElementType | any }
  formats?: MessageOptions["formats"]
  comment?: string
} & TransRenderCallbackOrComponent

/**
 * Version of `<Trans>` component without using a Provider/Context React feature.
 * Primarily made for support React Server Components (RSC)
 *
 * @experimental the api of this component is not stabilized yet.
 */
export function TransNoContext(
  props: TransProps & {
    lingui: {
      i18n: I18n
      defaultComponent?: React.ComponentType<TransRenderProps>
    }
  }
): React.ReactElement<any, any> | null {
  const {
    render,
    component,
    id,
    message,
    formats,
    lingui: { i18n, defaultComponent },
  } = props

  const { values, components } = getInterpolationValuesAndComponents(props)

  const _translation: string =
    i18n && typeof i18n._ === "function"
      ? i18n._(id, values, { message, formats })
      : id // i18n provider isn't loaded at all

  const translation = _translation
    ? formatElements(_translation, components)
    : null

  if (render === null || component === null) {
    // Although `string` is a valid react element, types only allow `Element`
    // Upstream issue: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/20544
    return translation as unknown as React.ReactElement<any, any>
  }

  const FallbackComponent: React.ComponentType<TransRenderProps> =
    defaultComponent || RenderFragment

  const i18nProps: TransRenderProps = {
    id,
    message,
    translation,
    children: translation, // for type-compatibility with `component` prop
  }

  // Validation of `render` and `component` props
  if (render && component) {
    console.error(
      "You can't use both `component` and `render` prop at the same time. `component` is ignored."
    )
  } else if (render && typeof render !== "function") {
    console.error(
      `Invalid value supplied to prop \`render\`. It must be a function, provided ${render}`
    )
  } else if (component && typeof component !== "function") {
    // Apparently, both function components and class components are functions
    // See https://stackoverflow.com/a/41658173/1535540
    console.error(
      `Invalid value supplied to prop \`component\`. It must be a React component, provided ${component}`
    )

    return <FallbackComponent {...i18nProps}>{translation}</FallbackComponent>
  }

  // Rendering using a render prop
  if (typeof render === "function") {
    // Component: render={(props) => <a title={props.translation}>x</a>}
    return render(i18nProps)
  }

  // `component` prop has a higher precedence over `defaultComponent`
  const Component: React.ComponentType<TransRenderProps> =
    component || FallbackComponent

  return <Component {...i18nProps}>{translation}</Component>
}

const RenderFragment = ({ children }: TransRenderProps) => {
  // cannot use React.Fragment directly because we're passing in props that it doesn't support
  return <>{children}</>
}

const getInterpolationValuesAndComponents = (props: TransProps) => {
  if (!props.values) {
    return {
      values: undefined,
      components: props.components,
    }
  }

  const values = { ...props.values }
  const components = { ...props.components }
  /*
      Replace values placeholders with <INDEX /> and add values to `components`.
      This makes them processed as JSX children and follow JSX semantics.

      Related discussion: https://github.com/lingui/js-lingui/issues/1904

      Another use-case is when React components are directly passed as values:

      Example:
      Translation: 'Hello {name}'
      Values: { name: <strong>Jane</strong> }

      It'll become "Hello <0 />" with components=[<strong>Jane</strong>]

      Related discussion: https://github.com/lingui/js-lingui/issues/183
    */
  Object.entries(props.values).forEach(([key, valueForKey]) => {
    // simple scalars should be processed as values to be able to apply formatting
    if (typeof valueForKey === "string" || typeof valueForKey === "number") {
      return
    }
    const index = Object.keys(components).length
    // react components, arrays, falsy values, all should be processed as JSX children
    components[index] = <>{valueForKey}</>
    values[key] = `<${index}/>`
  })
  return { values, components }
}
