// packages/vue/src/extractor/fixtures/macro.vue
<script setup lang="ts">
import { Trans, vt } from "@lingui/vue"
import { t, plural } from "@lingui/core/macro"

t`Hello from core macro`
const name = ""
const town = ""
const persona = ""
const count = 5
</script>

<template>
  <Trans>Simple Trans</Trans>
  <Trans context="another">Simple Trans</Trans>
  <Trans comment="this is a comment">Trans with Comment</Trans>

  <Trans id="some.id">Trans With Id</Trans>

  <Trans
    >Hello <em>{{ name }}</em> welcome to {{ town }} <br />
    <span
      >you are now
      <em
        ><i>a {{ persona }}</i></em
      ></span
    >!</Trans
  >

  <img :title="vt`Hello ${name}`" src="" />

  <img :title="plural(count, { one: '# book', other: '# books' })" src="" />
</template>

// packages/cli/src/api/fixtures/collect-typescript-jsx/macro.tsx
import { t, defineMessage, plural } from "@lingui/core/macro"
import { Trans } from "@lingui/react/macro"

// JS Macro usages
const msg = t`Message`

const withDescription = defineMessage({
  message: "Description",
  comment: "description",
})

const withTId = t({
  id: "ID Some",
  message: "Message with id some",
})

// JSX Macro usages
;<Trans>Hi, my name is {name}</Trans>
;<Trans context="Context1">Some message</Trans>
;<span title={t`Title`} />
;<span
  title={plural(count, {
    one: "# book",
    other: "# books",
  })}
/>
